# Generated by Django 5.2.16 on 2026-07-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], help_text='Préférence de genre pour les textes', max_length=1, verbose_name='Je préfère lire les textes au'),
        ),
    ]
