ALTER TABLE public.pauses_pause ADD created_at timestamptz NOT NULL;

ALTER TABLE public.pauses_need ADD need_family varchar(4) NOT NULL;

ALTER TABLE public.users_user ADD is_active bool NOT NULL;

-- Drop table

-- DROP TABLE public.pauses_pause_feelings;

CREATE TABLE public.pauses_pause_feelings (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	pause_id int8 NOT NULL,
	feeling_id int8 NOT NULL,
	CONSTRAINT pauses_pause_feelings_pause_id_feeling_id_dd4367aa_uniq UNIQUE (pause_id, feeling_id),
	CONSTRAINT pauses_pause_feelings_pkey PRIMARY KEY (id),
	CONSTRAINT pauses_pause_feelings_feeling_id_0b899adc_fk_pauses_feeling_id FOREIGN KEY (feeling_id) REFERENCES public.pauses_feeling(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT pauses_pause_feelings_pause_id_3a8fa038_fk_pauses_pause_id FOREIGN KEY (pause_id) REFERENCES public.pauses_pause(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX pauses_pause_feelings_feeling_id_0b899adc ON public.pauses_pause_feelings USING btree (feeling_id);
CREATE INDEX pauses_pause_feelings_pause_id_3a8fa038 ON public.pauses_pause_feelings USING btree (pause_id);

ALTER TABLE public.pauses_pause ADD empty_your_bag text NOT NULL;

ALTER TABLE public.pauses_feeling ADD feeling_family varchar(4) NOT NULL;

ALTER TABLE public.pauses_pause_feelings ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

ALTER TABLE public.users_user ADD "password" varchar(128) NOT NULL;

-- Drop table

-- DROP TABLE public.pauses_need;

CREATE TABLE public.pauses_need (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	need_family varchar(4) NOT NULL,
	CONSTRAINT pauses_need_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public.pauses_feeling;

CREATE TABLE public.pauses_feeling (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	feminine_name varchar(100) NOT NULL,
	masculine_name varchar(100) NOT NULL,
	feeling_family varchar(4) NOT NULL,
	CONSTRAINT pauses_feeling_pkey PRIMARY KEY (id)
);

ALTER TABLE public.pauses_pause ADD title varchar(200) NOT NULL;

ALTER TABLE public.pauses_pause_needs ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

-- Drop table

-- DROP TABLE public.users_user;

CREATE TABLE public.users_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	email varchar(254) NOT NULL,
	firstname varchar(150) NOT NULL,
	gender varchar(1) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	is_active bool NOT NULL,
	is_staff bool NOT NULL,
	CONSTRAINT users_user_email_key UNIQUE (email),
	CONSTRAINT users_user_pkey PRIMARY KEY (id)
);
CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);

ALTER TABLE public.pauses_pause ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

ALTER TABLE public.pauses_pause ADD observation text NOT NULL;

ALTER TABLE public.pauses_pause ADD user_id int8 NOT NULL;

ALTER TABLE public.users_user ADD updated_at timestamptz NOT NULL;

ALTER TABLE public.pauses_feeling ADD feminine_name varchar(100) NOT NULL;

ALTER TABLE public.pauses_need ADD "name" varchar(100) NOT NULL;

-- Drop table

-- DROP TABLE public.pauses_anonymouspausecounter;

CREATE TABLE public.pauses_anonymouspausecounter (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	count int4 NOT NULL,
	CONSTRAINT pauses_anonymouspausecounter_count_check CHECK ((count >= 0)),
	CONSTRAINT pauses_anonymouspausecounter_pkey PRIMARY KEY (id)
);

ALTER TABLE public.pauses_anonymouspausecounter ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

ALTER TABLE public.users_user ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

ALTER TABLE public.users_user ADD is_superuser bool NOT NULL;

ALTER TABLE public.users_user ADD firstname varchar(150) NOT NULL;

ALTER TABLE public.pauses_pause ADD updated_at timestamptz NOT NULL;

ALTER TABLE public.users_user ADD gender varchar(1) NOT NULL;

ALTER TABLE public.users_user ADD is_staff bool NOT NULL;

ALTER TABLE public.users_user ADD created_at timestamptz NOT NULL;

ALTER TABLE public.pauses_feeling ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

ALTER TABLE public.pauses_anonymouspausecounter ADD count int4 NOT NULL;

ALTER TABLE public.users_user ADD email varchar(254) NOT NULL;

-- Drop table

-- DROP TABLE public.pauses_pause_needs;

CREATE TABLE public.pauses_pause_needs (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	pause_id int8 NOT NULL,
	need_id int8 NOT NULL,
	CONSTRAINT pauses_pause_needs_pause_id_need_id_49dca9b8_uniq UNIQUE (pause_id, need_id),
	CONSTRAINT pauses_pause_needs_pkey PRIMARY KEY (id),
	CONSTRAINT pauses_pause_needs_need_id_a73c45d4_fk_pauses_need_id FOREIGN KEY (need_id) REFERENCES public.pauses_need(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT pauses_pause_needs_pause_id_6527021d_fk_pauses_pause_id FOREIGN KEY (pause_id) REFERENCES public.pauses_pause(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX pauses_pause_needs_need_id_a73c45d4 ON public.pauses_pause_needs USING btree (need_id);
CREATE INDEX pauses_pause_needs_pause_id_6527021d ON public.pauses_pause_needs USING btree (pause_id);

ALTER TABLE public.pauses_pause_needs ADD need_id int8 NOT NULL;

ALTER TABLE public.pauses_pause_feelings ADD feeling_id int8 NOT NULL;

ALTER TABLE public.pauses_pause_feelings ADD pause_id int8 NOT NULL;

ALTER TABLE public.pauses_need ADD id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL;

-- Drop table

-- DROP TABLE public.pauses_pause;

CREATE TABLE public.pauses_pause (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	empty_your_bag text NOT NULL,
	observation text NOT NULL,
	user_id int8 NOT NULL,
	title varchar(200) NOT NULL,
	CONSTRAINT pauses_pause_pkey PRIMARY KEY (id),
	CONSTRAINT pauses_pause_user_id_cbf747b7_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX pauses_pause_user_id_cbf747b7 ON public.pauses_pause USING btree (user_id);

ALTER TABLE public.pauses_pause_needs ADD pause_id int8 NOT NULL;

ALTER TABLE public.pauses_feeling ADD masculine_name varchar(100) NOT NULL;

ALTER TABLE public.users_user ADD last_login timestamptz NULL;
