# Generated by Django 5.2.6 on 2025-12-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pauses", "0003_alter_pause_options_pause_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pause",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Pause empathique",
                "verbose_name_plural": "Pauses empathiques",
            },
        ),
    ]
