# Generated by Django 5.2.12 on 2026-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauses', '0004_alter_pause_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pause',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name='Observation'),
        ),
    ]
