# Generated by Django 5.2.12 on 2026-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauses', '0005_alter_pause_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pause',
            name='feelings',
            field=models.ManyToManyField(related_name='pauses', to='pauses.feeling'),
        ),
        migrations.AlterField(
            model_name='pause',
            name='needs',
            field=models.ManyToManyField(related_name='pauses', to='pauses.need'),
        ),
    ]
