# Generated by Django 5.2.12 on 2026-05-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauses', '0006_alter_pause_feelings_alter_pause_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPauseCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de pauses anonymes',
            },
        ),
    ]
